/* Generated By:JavaCC: Do not edit this line. WEB_COMPILERConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WEB_COMPILERConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int qoute = 1;
  /** RegularExpression Id. */
  int alphanumeric = 2;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\"\"",
    "<alphanumeric>",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ADD \"",
    "\"IMAGE \"",
    "\"WITH \"",
    "\"SOURCE \"",
    "\"HEADING \"",
    "\"PARAGRAPH \"",
    "\"LINK \"",
    "\"TEXT \"",
    "\"COLOR \"",
    "\"FONT \"",
    "\" AND \"",
  };

}
